### ISSUE TITLE
more-examples for the Pi Hut Tree

### ISSUE THREAD

**Issue by GlynM001** [ppumkin/thepihut3dxmastree-examples#7]
Here is my attempt at creating an application for the Pi Hut Xmas tree.

It creates 4 different sequences of the LEDs in a random order. Two sequences can go in reverse directions making 6 unique sequences. Each sequence runs for between 3 & 10 seconds.

I have also optionally modified my tree with a button between the otherwise unused GPIO3 & ground.
This is to provide a clean shutdown method when used in a stand-alone mode.
The button is wired between pins 5 & 6 of the GPIO connector on the tree.
It can take a while for the program to spot that the shutdown button has been pushed. So hold the button in until the light sequence stops.

It is my first attempt at coding in Python on Lynux so apologies if it is not very elegant.

I am also new to github as so I hope this works and you can find my code here:

https://github.com/GlynM001/Raspberry-pi-stuff/blob/master/xmas_tree_multi_random_function_VF2.py

**Comment by p10tyr** [comment]
Great! Thanks allot for sharing.
Since you are new to github too, I would suggest trying to fork and merge back here as an exercise.

1. Create a gituhub account
2. Come to this repository and press fork in the top right (Fork will make a copy of this repository in YOUR account)
3. Install GIT on Linux
4. git pull <your url to your fork>
5. create and change to a new branch `git checkout <a-branch-name>`
6. Add your file into the `/examples` folder
7. Add your files to be staged with  `git add .` (there is a dot on the end which means all)
8. Commit your files to you local repository `git commit -a -m "Your commit message here"`
9. Git push (you will have to enter your credentials)
10. Go back to YOUR GIT in the browser and click on `New Pull Request`
11. You should have it set automatically. (Left) your repo and branch -> (Right) this one
12. When you click raise PR it will come into PR on this one I can then merge it in for everybody

Seems quite complex at first but it is worth learning. If you get stuck let us know here or have a search on stack overflow. 

That way you can keep your own repository and branches and if you update something it is easy to push it up to this main collection for everybody to benefit.

Thanks again!

**Comment by GlynM001** [comment]
It took a while and I had to do several attempts but I believe that I have succeeded in creating a pull request for my example.

It is a slightly different version to the file that I originally posted in that I have corrected some spelling mistakes in the comments. However there are no changes to the actual code.
Thanks for your help.

**Comment by p10tyr** [comment]
Thank you very much for this. I hope we see more examples from you. I can't wait to get this going tonight 😍

**Comment by djfatal** [comment]
Well done. I love this!
